### PR TITLE
[TECHNICAL SUPPORT] LPS-122216 Tweak

### PR DESCRIPTION
**Pull request by stian-sigvartsen**
Hi Rodrigo. Sorry for the delay in this review. Please can you check you are happy and ci:forward?

### CODE REVIEW

**Comment by stian-sigvartsen** [comment]
ci:test:relevant

**Comment by rodrigopaulino** [comment]
LGTM, @stian-sigvartsen 

Do you mind me forwarding directly to Brian, or do you still need me to send the LPS back to the team?

**Comment by rodrigopaulino** [comment]
ci:forward

**Comment by rodrigopaulino** [comment]
ci:forward

**Pull request closed without merging**
