### PR TITLE
LPS-105077 SF

### PR DESCRIPTION
**Pull request by leoadb**

### CODE REVIEW

**Comment by leoadb** [comment]
@rodrigopaulino can you please fix the tests on top of my changes? Please see the broken tests in https://github.com/leoadb/liferay-portal/pull/631

**Comment by rodrigopaulino** [comment]
Just started reviewing :)

**Comment by rodrigopaulino** [comment]
ci:test:relevant

**Comment by rodrigopaulino** [comment]
ci:stop

**Comment by rodrigopaulino** [comment]
Pull request submitted to https://github.com/leoadb/liferay-portal/pull/632. [See changes here.](https://github.com/rodrigopaulino/liferay-portal/compare/94b56744c93d~1...94b56744c93d)

**Pull request closed without merging**
