### PR TITLE
[Technical Support] MASTER - LPS-122339

### PR DESCRIPTION
**Pull request by rijema**
Click [here](https://issues.liferay.com/browse/LPS-122339) to see the LPS

### CODE REVIEW

**Comment by rijema** [comment]
ci:test:sf

**Comment by rijema** [comment]
ci:test:relevant

**Comment by rodrigopaulino** [comment]
Just started reviewing :)

**Comment by rodrigopaulino** [comment]
Pull request forwarded to https://github.com/liferay-forms/liferay-portal/pull/33.

**Pull request closed without merging**
