### PR TITLE
LPS-92361 Uses a new param to show the selected roles when we are unassigning them or show not selected roles when we are assigning them

### PR DESCRIPTION
**Pull request by ealonso**
Hey @rodrigopaulino,

Could you please check if this solution fix your problems? After talking with @jbalsas we decided to split the action in two actions since we have a known problem with search container, pagination and selected checkboxes.

If everything is ok for you, please send it to Brian.

Regards,
Eudaldo.

### CODE REVIEW

**Comment by rodrigopaulino** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rodrigopaulino** [comment]
> Hey @rodrigopaulino,
> 
> Could you please check if this solution fix your problems? After talking with @jbalsas we decided to split the action in two actions since we have a known problem with search container, pagination and selected checkboxes.
> 
> If everything is ok for you, please send it to Brian.
> 
> Regards,
> Eudaldo.

Hey, @ealonso.

Sorry for the late response but I was only able to review this today.
I've checked out your code and it seems to resolve the customer's problem.
Unfortunately, I believe this won't pass the backport review due to this approach of changing the UX. So I won't have any other choice but sending my code, that I think you've reviewed, to the ".x" branches. Do you have any notes on that proposed fix? If so, please let me know as it will help me prevent possible regressions in the future.

Thanks for taking the time to fix this.
Best regards.

**Comment by dacousalr** [comment]
Just started reviewing :)

**Comment by dacousalr** [comment]
Just started reviewing :)

**Comment by dacousalr** [comment]
Hi @rodrigopaulino,

I have reviewed this by @ealonso's request and I think that this could be backported to 7.1 and 7.0 as long as it includes a System Setting that after being enabled takes this solution into effect but when disabled (default value) then the behavior is the current one.

What do you think?

**Comment by rodrigopaulino** [comment]
That'd be great, @dacousalr!
I'll include this setting on my backport pull requests, then!
Thanks a lot for reviewing this and giving your insights.

**Comment by dacousalr** [comment]
Thanks to you for all your work on this, @rodrigopaulino!

**Pull request closed without merging**
